"""
Script for identifying which high-level categories are present in a text, and 
High-level categories are taken from the THINGS+ dataset (generated by WordNet).
"""
import argparse
import mne
import os 

from ZW_get_categories_func import category_raw, epoching, mvnn, save_prepr

parser = argparse.ArgumentParser()
parser.add_argument('--project_dir', default='../project_directory', type=str)
parser.add_argument('--category', default='food', type=str)
parser.add_argument('--sfreq', default=100, type=int)
parser.add_argument('--chunk_size', default='100', type=int)
parser.add_argument('--mvnn_dim', default='time', type=str)
args = parser.parse_args()

##############################################################################
# Preprocess the raw EEG file under one specifc dream category
##############################################################################
IDs = category_raw(args)

# The list of all PSG file names
Zhang_dir = os.path.join(args.project_dir, 'eeg_dataset', 'dream_data',
                         'Zhang_Wamsley')
import_path_PSG = os.path.join(Zhang_dir, 'Data', 'PSG')
PSGs = os.listdir(import_path_PSG)

# Iterate over selected dreams
for ID in IDs: 
    for PSG in PSGs:
        if ID == PSG[7:-4]:
            raw = mne.io.read_raw_edf(os.path.join(import_path_PSG, PSG))
            data, ch_names, times = epoching(args, raw)
            whitened_data = mvnn(args, data)
            save_prepr(args, whitened_data, ch_names, times, ID)
            del raw, data, ch_names, times